# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Chris/Desktop/Research/Boost_Control/Boost_Control.srcs/sources_1/ip/step_counter/step_counter.xci
# IP: The module: 'step_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chris/Desktop/Research/Boost_Control/Boost_Control.srcs/sources_1/ip/step_counter/step_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'step_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Chris/Desktop/Research/Boost_Control/Boost_Control.srcs/sources_1/ip/step_counter/step_counter.xci
# IP: The module: 'step_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chris/Desktop/Research/Boost_Control/Boost_Control.srcs/sources_1/ip/step_counter/step_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'step_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
